# hash:sha256:2c831babc2e0cd7a291f7eb72c7de067bf995642980e4dd8596ca4d66425bc33
FROM registry.codeocean.com/codeocean/miniconda3:4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    numpy==1.24.3 \
    pandas==2.0.1 \
    scikit-learn==1.2.2
